version: 0.0
os: linux
files:
  - source: /
    destination: /var/lib/tomcat8/webapps/1.war
  - source: /scripts/configure_http_port.xsl
    destination: /var/lib/tomcat8/webapps/
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_application
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh
